//! GENERATED by server/gen_routes.py from ../src-tauri/src. Do not edit by hand.
#![allow(clippy::all, unused_imports, unused_variables, non_snake_case)]
use axum::extract::State;
use axum::routing::post;
use axum::{Json, Router};
use serde::Deserialize;
use std::path::PathBuf;

use en_croissant::chess::*;
use en_croissant::db::*;
use en_croissant::engine::*;
use en_croissant::lexer::*;
use en_croissant::opening::*;
use en_croissant::pgn::*;
use en_croissant::progress::*;
use en_croissant::fs::*;

use crate::app::{ApiResult, App};
use crate::paths::{resolve, resolve_all, resolve_engine};

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KillEnginesArgs {
    pub tab: String,
}

pub async fn kill_engines(State(app): State<App>, Json(args): Json<KillEnginesArgs>) -> ApiResult {
    app.touch_tab(&args.tab);
    let out = en_croissant::chess::kill_engines(args.tab, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KillEngineArgs {
    pub engine: String,
    pub tab: String,
}

pub async fn kill_engine(State(app): State<App>, Json(args): Json<KillEngineArgs>) -> ApiResult {
    app.touch_tab(&args.tab);
    let out = en_croissant::chess::kill_engine(args.engine, args.tab, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StopEngineArgs {
    pub engine: String,
    pub tab: String,
}

pub async fn stop_engine(State(app): State<App>, Json(args): Json<StopEngineArgs>) -> ApiResult {
    app.touch_tab(&args.tab);
    let out = en_croissant::chess::stop_engine(args.engine, args.tab, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetEngineLogsArgs {
    pub engine: String,
    pub tab: String,
}

pub async fn get_engine_logs(State(app): State<App>, Json(args): Json<GetEngineLogsArgs>) -> ApiResult {
    app.touch_tab(&args.tab);
    let out = en_croissant::chess::get_engine_logs(args.engine, args.tab, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetBestMovesArgs {
    pub id: String,
    pub engine: String,
    pub tab: String,
    pub go_mode: GoMode,
    pub options: EngineOptions,
}

pub async fn get_best_moves(State(app): State<App>, Json(args): Json<GetBestMovesArgs>) -> ApiResult {
    app.touch_tab(&args.tab);
    let engine = resolve_engine(&app.ctx.data_dir, &args.engine)?.to_string_lossy().into_owned();
    let app2 = app.clone();
    let handle = tokio::spawn(async move { en_croissant::chess::get_best_moves(args.id, engine, args.tab, args.go_mode, args.options, app2.ctx.clone(), &*app2.ctx.state).await });
    match tokio::time::timeout(std::time::Duration::from_millis(300), handle).await {
        Ok(Ok(Ok(out))) => Ok(Json(serde_json::to_value(out)?)),
        Ok(Ok(Err(e))) => Err(e.into()),
        Ok(Err(join)) => Err(crate::app::ApiError(join.to_string())),
        Err(_elapsed) => Ok(Json(serde_json::Value::Null)), // still running; results arrive as events
    }
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CancelAnalysisArgs {
    pub id: String,
}

pub async fn cancel_analysis(State(app): State<App>, Json(args): Json<CancelAnalysisArgs>) -> ApiResult {
    let out = en_croissant::chess::cancel_analysis(args.id, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetEngineConfigArgs {
    pub path: String,
}

pub async fn get_engine_config(State(app): State<App>, Json(args): Json<GetEngineConfigArgs>) -> ApiResult {
    let out = en_croissant::chess::get_engine_config(resolve_engine(&app.ctx.data_dir, &args.path)?).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConvertPgnArgs {
    pub files: Vec<String>,
    pub db_path: String,
    pub timestamp: Option<i32>,
    pub title: String,
    pub description: Option<String>,
}

pub async fn convert_pgn(State(app): State<App>, Json(args): Json<ConvertPgnArgs>) -> ApiResult {
    let out = en_croissant::db::convert_pgn(resolve_all(&app.ctx.data_dir, &args.files)?, resolve(&app.ctx.data_dir, &args.db_path)?, args.timestamp, app.ctx.clone(), args.title, args.description, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetDbInfoArgs {
    pub file: String,
}

pub async fn get_db_info(State(app): State<App>, Json(args): Json<GetDbInfoArgs>) -> ApiResult {
    let out = en_croissant::db::get_db_info(resolve(&app.ctx.data_dir, &args.file)?, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateIndexesArgs {
    pub file: String,
}

pub async fn create_indexes(State(app): State<App>, Json(args): Json<CreateIndexesArgs>) -> ApiResult {
    let out = en_croissant::db::create_indexes(resolve(&app.ctx.data_dir, &args.file)?, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteIndexesArgs {
    pub file: String,
}

pub async fn delete_indexes(State(app): State<App>, Json(args): Json<DeleteIndexesArgs>) -> ApiResult {
    let out = en_croissant::db::delete_indexes(resolve(&app.ctx.data_dir, &args.file)?, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EditDbInfoArgs {
    pub file: String,
    pub title: Option<String>,
    pub description: Option<String>,
}

pub async fn edit_db_info(State(app): State<App>, Json(args): Json<EditDbInfoArgs>) -> ApiResult {
    let out = en_croissant::db::edit_db_info(resolve(&app.ctx.data_dir, &args.file)?, args.title, args.description, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetGamesArgs {
    pub file: String,
    pub query: GameQuery,
}

pub async fn get_games(State(app): State<App>, Json(args): Json<GetGamesArgs>) -> ApiResult {
    let out = en_croissant::db::get_games(resolve(&app.ctx.data_dir, &args.file)?, args.query, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetPlayerArgs {
    pub file: String,
    pub id: i32,
}

pub async fn get_player(State(app): State<App>, Json(args): Json<GetPlayerArgs>) -> ApiResult {
    let out = en_croissant::db::get_player(resolve(&app.ctx.data_dir, &args.file)?, args.id, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetPlayersArgs {
    pub file: String,
    pub query: PlayerQuery,
}

pub async fn get_players(State(app): State<App>, Json(args): Json<GetPlayersArgs>) -> ApiResult {
    let out = en_croissant::db::get_players(resolve(&app.ctx.data_dir, &args.file)?, args.query, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetTournamentsArgs {
    pub file: String,
    pub query: TournamentQuery,
}

pub async fn get_tournaments(State(app): State<App>, Json(args): Json<GetTournamentsArgs>) -> ApiResult {
    let out = en_croissant::db::get_tournaments(resolve(&app.ctx.data_dir, &args.file)?, args.query, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetPlayersGameInfoArgs {
    pub file: String,
    pub id: i32,
}

pub async fn get_players_game_info(State(app): State<App>, Json(args): Json<GetPlayersGameInfoArgs>) -> ApiResult {
    let out = en_croissant::db::get_players_game_info(resolve(&app.ctx.data_dir, &args.file)?, args.id, &*app.ctx.state, app.ctx.clone()).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteDatabaseArgs {
    pub file: String,
}

pub async fn delete_database(State(app): State<App>, Json(args): Json<DeleteDatabaseArgs>) -> ApiResult {
    let out = en_croissant::db::delete_database(resolve(&app.ctx.data_dir, &args.file)?, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteDuplicatedGamesArgs {
    pub file: String,
}

pub async fn delete_duplicated_games(State(app): State<App>, Json(args): Json<DeleteDuplicatedGamesArgs>) -> ApiResult {
    let out = en_croissant::db::delete_duplicated_games(resolve(&app.ctx.data_dir, &args.file)?, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteEmptyGamesArgs {
    pub file: String,
}

pub async fn delete_empty_games(State(app): State<App>, Json(args): Json<DeleteEmptyGamesArgs>) -> ApiResult {
    let out = en_croissant::db::delete_empty_games(resolve(&app.ctx.data_dir, &args.file)?, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExportToPgnArgs {
    pub file: String,
    pub dest_file: String,
}

pub async fn export_to_pgn(State(app): State<App>, Json(args): Json<ExportToPgnArgs>) -> ApiResult {
    let out = en_croissant::db::export_to_pgn(resolve(&app.ctx.data_dir, &args.file)?, resolve(&app.ctx.data_dir, &args.dest_file)?, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteDbGameArgs {
    pub file: String,
    pub game_id: i32,
}

pub async fn delete_db_game(State(app): State<App>, Json(args): Json<DeleteDbGameArgs>) -> ApiResult {
    let out = en_croissant::db::delete_db_game(resolve(&app.ctx.data_dir, &args.file)?, args.game_id, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WriteDbGameArgs {
    pub file: String,
    pub game_id: i32,
    pub pgn: String,
}

pub async fn write_db_game(State(app): State<App>, Json(args): Json<WriteDbGameArgs>) -> ApiResult {
    let out = en_croissant::db::write_db_game(resolve(&app.ctx.data_dir, &args.file)?, args.game_id, args.pgn, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MergePlayersArgs {
    pub file: String,
    pub player1: i32,
    pub player2: i32,
}

pub async fn merge_players(State(app): State<App>, Json(args): Json<MergePlayersArgs>) -> ApiResult {
    let out = en_croissant::db::merge_players(resolve(&app.ctx.data_dir, &args.file)?, args.player1, args.player2, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClearGamesArgs {
}

pub async fn clear_games(State(app): State<App>, Json(args): Json<ClearGamesArgs>) -> ApiResult {
    let _ = &args;
    let out = en_croissant::db::clear_games(&*app.ctx.state);
    let () = out;
    Ok(Json(serde_json::Value::Null))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PreloadReferenceDbArgs {
    pub file: String,
}

pub async fn preload_reference_db(State(app): State<App>, Json(args): Json<PreloadReferenceDbArgs>) -> ApiResult {
    let out = en_croissant::db::preload_reference_db(resolve(&app.ctx.data_dir, &args.file)?, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchPositionArgs {
    pub file: String,
    pub query: GameQuery,
    pub tab_id: String,
}

pub async fn search_position(State(app): State<App>, Json(args): Json<SearchPositionArgs>) -> ApiResult {
    app.touch_tab(&args.tab_id);
    let out = en_croissant::db::search_position(resolve(&app.ctx.data_dir, &args.file)?, args.query, app.ctx.clone(), args.tab_id, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileExistsArgs {
    pub path: String,
}

pub async fn file_exists(State(app): State<App>, Json(args): Json<FileExistsArgs>) -> ApiResult {
    let out = en_croissant::fs::file_exists(resolve(&app.ctx.data_dir, &args.path)?.to_string_lossy().into_owned()).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetFileMetadataArgs {
    pub path: String,
}

pub async fn get_file_metadata(State(app): State<App>, Json(args): Json<GetFileMetadataArgs>) -> ApiResult {
    let out = en_croissant::fs::get_file_metadata(resolve(&app.ctx.data_dir, &args.path)?.to_string_lossy().into_owned()).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetGameStateArgs {
    pub game_id: String,
}

pub async fn get_game_state(State(app): State<App>, Json(args): Json<GetGameStateArgs>) -> ApiResult {
    app.touch_game(&args.game_id);
    let out = en_croissant::game::get_game_state(args.game_id, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MakeGameMoveArgs {
    pub game_id: String,
    pub uci: String,
}

pub async fn make_game_move(State(app): State<App>, Json(args): Json<MakeGameMoveArgs>) -> ApiResult {
    app.touch_game(&args.game_id);
    let out = en_croissant::game::make_game_move(args.game_id, args.uci, app.ctx.clone(), &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TakeBackGameMoveArgs {
    pub game_id: String,
}

pub async fn take_back_game_move(State(app): State<App>, Json(args): Json<TakeBackGameMoveArgs>) -> ApiResult {
    app.touch_game(&args.game_id);
    let out = en_croissant::game::take_back_game_move(args.game_id, app.ctx.clone(), &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResignGameArgs {
    pub game_id: String,
    pub color: String,
}

pub async fn resign_game(State(app): State<App>, Json(args): Json<ResignGameArgs>) -> ApiResult {
    app.touch_game(&args.game_id);
    let out = en_croissant::game::resign_game(args.game_id, args.color, app.ctx.clone(), &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AbortGameArgs {
    pub game_id: String,
}

pub async fn abort_game(State(app): State<App>, Json(args): Json<AbortGameArgs>) -> ApiResult {
    app.touch_game(&args.game_id);
    let out = en_croissant::game::abort_game(args.game_id, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetGameEngineLogsArgs {
    pub game_id: String,
    pub color: String,
}

pub async fn get_game_engine_logs(State(app): State<App>, Json(args): Json<GetGameEngineLogsArgs>) -> ApiResult {
    app.touch_game(&args.game_id);
    let out = en_croissant::game::get_game_engine_logs(args.game_id, args.color, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LexPgnArgs {
    pub pgn: String,
}

pub async fn lex_pgn(State(app): State<App>, Json(args): Json<LexPgnArgs>) -> ApiResult {
    let out = en_croissant::lexer::lex_pgn(args.pgn).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetOpeningFromFenArgs {
    pub fen: String,
}

pub async fn get_opening_from_fen(State(app): State<App>, Json(args): Json<GetOpeningFromFenArgs>) -> ApiResult {
    let out = en_croissant::opening::get_opening_from_fen(&args.fen)?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetOpeningFromNameArgs {
    pub name: String,
}

pub async fn get_opening_from_name(State(app): State<App>, Json(args): Json<GetOpeningFromNameArgs>) -> ApiResult {
    let out = en_croissant::opening::get_opening_from_name(&args.name)?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetOpeningFromFensArgs {
    pub fens: Vec<String>,
}

pub async fn get_opening_from_fens(State(app): State<App>, Json(args): Json<GetOpeningFromFensArgs>) -> ApiResult {
    let out = en_croissant::opening::get_opening_from_fens(args.fens)?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchOpeningNameArgs {
    pub query: String,
}

pub async fn search_opening_name(State(app): State<App>, Json(args): Json<SearchOpeningNameArgs>) -> ApiResult {
    let out = en_croissant::opening::search_opening_name(args.query).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CountPgnGamesArgs {
    pub file: String,
}

pub async fn count_pgn_games(State(app): State<App>, Json(args): Json<CountPgnGamesArgs>) -> ApiResult {
    let out = en_croissant::pgn::count_pgn_games(resolve(&app.ctx.data_dir, &args.file)?, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadGamesArgs {
    pub file: String,
    pub start: i32,
    pub end: i32,
}

pub async fn read_games(State(app): State<App>, Json(args): Json<ReadGamesArgs>) -> ApiResult {
    let out = en_croissant::pgn::read_games(resolve(&app.ctx.data_dir, &args.file)?, args.start, args.end, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteGameArgs {
    pub file: String,
    pub n: i32,
}

pub async fn delete_game(State(app): State<App>, Json(args): Json<DeleteGameArgs>) -> ApiResult {
    let out = en_croissant::pgn::delete_game(resolve(&app.ctx.data_dir, &args.file)?, args.n, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WriteGameArgs {
    pub file_path: String,
    pub n: i32,
    pub pgn: String,
}

pub async fn write_game(State(app): State<App>, Json(args): Json<WriteGameArgs>) -> ApiResult {
    let out = en_croissant::pgn::write_game(resolve(&app.ctx.data_dir, &args.file_path)?.to_string_lossy().into_owned(), args.n, args.pgn, &*app.ctx.state).await?;
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetProgressArgs {
    pub id: String,
}

pub async fn get_progress(State(app): State<App>, Json(args): Json<GetProgressArgs>) -> ApiResult {
    let out = en_croissant::progress::get_progress(args.id, &*app.ctx.state);
    Ok(Json(serde_json::to_value(out)?))
}


#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClearProgressArgs {
    pub id: String,
}

pub async fn clear_progress(State(app): State<App>, Json(args): Json<ClearProgressArgs>) -> ApiResult {
    let out = en_croissant::progress::clear_progress(args.id, &*app.ctx.state);
    Ok(Json(serde_json::to_value(out)?))
}


pub fn router() -> Router<App> {
    Router::new()
        .route("/api/cmd/kill_engines", post(kill_engines))
        .route("/api/cmd/kill_engine", post(kill_engine))
        .route("/api/cmd/stop_engine", post(stop_engine))
        .route("/api/cmd/get_engine_logs", post(get_engine_logs))
        .route("/api/cmd/get_best_moves", post(get_best_moves))
        .route("/api/cmd/cancel_analysis", post(cancel_analysis))
        .route("/api/cmd/get_engine_config", post(get_engine_config))
        .route("/api/cmd/convert_pgn", post(convert_pgn))
        .route("/api/cmd/get_db_info", post(get_db_info))
        .route("/api/cmd/create_indexes", post(create_indexes))
        .route("/api/cmd/delete_indexes", post(delete_indexes))
        .route("/api/cmd/edit_db_info", post(edit_db_info))
        .route("/api/cmd/get_games", post(get_games))
        .route("/api/cmd/get_player", post(get_player))
        .route("/api/cmd/get_players", post(get_players))
        .route("/api/cmd/get_tournaments", post(get_tournaments))
        .route("/api/cmd/get_players_game_info", post(get_players_game_info))
        .route("/api/cmd/delete_database", post(delete_database))
        .route("/api/cmd/delete_duplicated_games", post(delete_duplicated_games))
        .route("/api/cmd/delete_empty_games", post(delete_empty_games))
        .route("/api/cmd/export_to_pgn", post(export_to_pgn))
        .route("/api/cmd/delete_db_game", post(delete_db_game))
        .route("/api/cmd/write_db_game", post(write_db_game))
        .route("/api/cmd/merge_players", post(merge_players))
        .route("/api/cmd/clear_games", post(clear_games))
        .route("/api/cmd/preload_reference_db", post(preload_reference_db))
        .route("/api/cmd/search_position", post(search_position))
        .route("/api/cmd/file_exists", post(file_exists))
        .route("/api/cmd/get_file_metadata", post(get_file_metadata))
        .route("/api/cmd/get_game_state", post(get_game_state))
        .route("/api/cmd/make_game_move", post(make_game_move))
        .route("/api/cmd/take_back_game_move", post(take_back_game_move))
        .route("/api/cmd/resign_game", post(resign_game))
        .route("/api/cmd/abort_game", post(abort_game))
        .route("/api/cmd/get_game_engine_logs", post(get_game_engine_logs))
        .route("/api/cmd/lex_pgn", post(lex_pgn))
        .route("/api/cmd/get_opening_from_fen", post(get_opening_from_fen))
        .route("/api/cmd/get_opening_from_name", post(get_opening_from_name))
        .route("/api/cmd/get_opening_from_fens", post(get_opening_from_fens))
        .route("/api/cmd/search_opening_name", post(search_opening_name))
        .route("/api/cmd/count_pgn_games", post(count_pgn_games))
        .route("/api/cmd/read_games", post(read_games))
        .route("/api/cmd/delete_game", post(delete_game))
        .route("/api/cmd/write_game", post(write_game))
        .route("/api/cmd/get_progress", post(get_progress))
        .route("/api/cmd/clear_progress", post(clear_progress))
}
